### ISSUE TITLE
addReceiver, removeReceiver, and removeReceivers are not thread safe

### ISSUE THREAD

**Issue by wallstop** [Valkryst/VRadio#1]
While you are using a ConcurrentDictionary, which is great, these two methods are not thread safe.

[addReceiver](https://github.com/Valkryst/VRadio/blob/1358eb1176432173215146a0b04e14afb9bee32c/src/com/valkryst/VRadio/Radio.java#L56)

Consider. N threads can call add on the same HashSet concurrently. HashSet is not threadsafe.

[removeReceiver](https://github.com/Valkryst/VRadio/blob/1358eb1176432173215146a0b04e14afb9bee32c/src/com/valkryst/VRadio/Radio.java#L75)

N threads can call remove on the same Hashset concurrently (with different arguments). Again, not threadsafe.

[removeReceivers](https://github.com/Valkryst/VRadio/blob/1358eb1176432173215146a0b04e14afb9bee32c/src/com/valkryst/VRadio/Radio.java#L89)

Threads can concurrently be adding and clearing this hashset.

In order to remedy these, you're going to want to take advantage of the concurrent features that ConcurrentDictionary has to offer, such as [compute](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#compute-K-java.util.function.BiFunction-) or [merge](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#merge-K-V-java.util.function.BiFunction-)

**Comment by wallstop** [comment]
A word of warning - the compute and merge functions can themselves by run concurrently, so you'll likely want to be returning entirely new copies of the hashsets, instead of simply calling .add/remove/etc on them.

**Comment by Valkryst** [comment]
Thanks for taking a look at the code. I had a sneaking suspicion that something wasn't right, but I couldn't put my finger on it until now.

I'm considering switching from HashSet to [ConcurrentSkipListSet](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentSkipListSet.html), what do you think?

**Comment by wallstop** [comment]
ConcurrentSkipListSet will solve the concurrency problems :) But it also changes the container properties (O(log(n)) from O(n))

Sets in the java std library tend to [be implemented as a Map<T, null>](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/HashSet.java#93). This means you could also do something like [this](https://stackoverflow.com/a/6992643/1917135) (set from map)

**Comment by Valkryst** [comment]
Thanks for the help. I've updated the Radio class to make use of *newKeySet()* over HashSet.
